ffn:
  var_groups: ['pos','vel']
  general:
    Delta: 20
    tau_prime: 14
  opt:
    num_units: [50,600]
    num_layers: [1,10]
    frac_dropout: [0,0.5]
    num_epochs: [2,30]
    init_points: 10
    n_iter: 10
    kappa: 10
    val_frac: 0.2
  pos:
    num_units: 546
    num_layers: 6
    frac_dropout: 0.03
    num_epochs: 16
  vel:
    num_units: 288
    num_layers: 8
    frac_dropout: 0.02
    num_epochs: 24
gru:
  var_groups: ['pos','vel']
  general:
    Delta: 20
    tau_prime: 14
  opt:
    num_units: [50,600]
    frac_dropout: [0,0.5]
    num_epochs: [2,30]
    init_points: 10
    n_iter: 10
    kappa: 10
    val_frac: 0.2
  pos:
    num_units: 581
    frac_dropout: 0.24
    num_epochs: 22
  vel:
    num_units: 532
    frac_dropout: 0.10
    num_epochs: 12
