ffn:
  var_groups: ['pos','vel']
  general:
    Bin_Size: 16
    tau_prime: 12
  opt:
    num_units: [50,600]
    num_layers: [1,10]
    frac_dropout: [0,0.5]
    num_epochs: [2,30]
    init_points: 10
    n_iter: 10
    kappa: 10
    val_frac: 0.2
  pos:
    num_units: 512
    num_layers: 6
    frac_dropout: 0.3
    num_epochs: 3
  vel:
    num_units: 564
    num_layers: 8
    frac_dropout: 0.12
    num_epochs: 3
gru:
  var_groups: ['pos','vel']
  general:
    Bin_Size: 20
    tau_prime: 14
  opt:
    num_units: [50,600]
    frac_dropout: [0,0.5]
    num_epochs: [2,30]
    init_points: 10
    n_iter: 10
    kappa: 10
    val_frac: 0.2
  pos:
    num_units: 320
    frac_dropout: 0.15
    num_epochs: 8
  vel:
    num_units: 573
    frac_dropout: 0.01
    num_epochs: 15
